import Head from "next/head";
import Header from "../src/components/header/header";
import Layout from "../src/components/layout/layout";

export default function Home() {
  return (
    <div>
      <Layout>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </Layout>
    </div>
  );
}
